name: GitHub actions scan and build application
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to get git repository informations
branding:
  icon: feather
  color: gray-dark

runs:
  using: "composite"
  steps:    
    - name: SonarQube scan
      shell: bash
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: MVN Package
      shell: bash
      run: mvn -B package --file pom.xml -DskipTests